# Generated by Django 3.2.5 on 2021-07-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(default=myapp.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='tasktouser', to=settings.AUTH_USER_MODEL),
        ),
    ]
