# Generated by Django 3.2.5 on 2021-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], max_length=300),
        ),
    ]
